  import React from 'react';
  import './Overview.css';
  import { ReactComponent as YourSvg } from './Online games addiction-amico.svg';


  const Overview = () => {
      return(
        <div id = "body">
                <Header/>
                <Image/>
                <Card
                  className='section'
                  title='HOLLY ROLLY POLLY!' 
                  description='A simple game of roll the dice. Player will have to guess the random number generated by RNG. 
                  If they got it right, they will be credited a bonus amount of tokens + the tokens they initially invest. 
                  Otherwise, they do not win anything. 
                  '
                  join='JOIN GAME'
                />

                <Card 
                    className='section'
                    img='./Capture3.PNG' 
                    title='GAME #2'
                    description='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                    eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
                    minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                    aliquip ex ea commodo consequat. Duis aute irure dolor in
                    reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
                    pariatur.'
                    join='JOIN GAME'
                      />

                <Card 
                    className='section'
                    img='./Capture3.PNG' 
                    title='GAME #3'
                    description='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                    eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
                    minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                    aliquip ex ea commodo consequat. Duis aute irure dolor in
                    reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
                    pariatur.'
                    join='JOIN GAME'
                      />
                <Wave/>
              </div>
      )
    }

    const Header = () => {
      return(
        <div className= 'header'>
          <span className= 'header-title'>
            WELCOME TO THE LOTTERY GAME
          </span>
          <br/>
        </div>
      );
    }

    const Image = () => {
      return(
        <div className= 'logo'>
          <YourSvg style={{ height: 300, width: 300}}/>
          
          </div>
      )
    }

    const Card = (props) =>{
      return(
        <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gridGap: 20 }}>
          <div></div>
          <div className={props.className} >
              <div className="small-div">
                  <i className={props.className}></i>
                  <img src={props.img} alt=''/>
              </div>

              <div className="big-div">
                  <span className='div-title'>
                      {props.title}
                  </span>
                  <br/>
                  <span className='div-description'>
                      {props.description}
                  </span>
              </div>
              <br/>
              <div className="join-game">
                <span className='join-game'>
                  {props.join}
                </span>
              </div>
              
          </div>
          </div>
      )
    }

    const Wave = () => {
      return(
        <svg height="100%" width="100%" id="bg-svg" viewBox="0 0 1440 500" xmlns="http://www.w3.org/2000/svg" 
        class="transition duration-300 ease-in-out delay-150"><defs><linearGradient id="gradient"><stop offset="5%" 
        stop-color="#9b7bc488"></stop><stop offset="95%" stop-color="#374b8c88"></stop></linearGradient></defs>
        <path d="M 0,500 C 0,500 0,166 0,166 C 108.42105263157893,194.86124401913878 216.84210526315786,223.72248803827753 319,
        207 C 421.15789473684214,190.27751196172247 517.0526315789474,127.97129186602871 618,112 C 718.9473684210526,
        96.02870813397129 824.9473684210525,126.39234449760764 900,154 C 975.0526315789475,181.60765550239236 1019.1578947368423,
        206.45933014354068 1104,208 C 1188.8421052631577,209.54066985645932 1314.4210526315787,187.77033492822966 1440,166 C 1440,
        166 1440,500 1440,500 Z" stroke="none" stroke-width="0" fill="url(#gradient)" class="transition-all duration-300 ease-in-out 
        delay-150"></path><defs><linearGradient id="gradient"><stop offset="5%" stop-color="#9b7bc4ff"></stop><stop offset="95%" 
        stop-color="#374b8cff"></stop></linearGradient></defs><path d="M 0,500 C 0,500 0,333 0,333 C 88.99521531100481,
        306.18660287081343 177.99043062200963,279.3732057416268 268,288 C 358.0095693779904,296.6267942583732 449.0334928229664,
        340.69377990430627 547,335 C 644.9665071770336,329.30622009569373 749.8755980861246,273.85167464114835 865,271 C 980.1244019138754,
        268.14832535885165 1105.4641148325359,317.8995215311005 1203,337 C 1300.5358851674641,356.1004784688995 1370.267942583732,
        344.55023923444975 1440,333 C 1440,333 1440,500 1440,500 Z" stroke="none" stroke-width="0" fill="url(#gradient)" 
        class="transition-all duration-300 ease-in-out delay-150"></path></svg>
      )
    }

  export default Overview;