import React from 'react';
import { ReactComponent as YourSvg } from './Online games addiction-amico.svg';
import './Overview.css';

const Overview = () => {
    return(
      <div id = "body">
              <Wave/>
              <Header/>
              <Image/>
              <Card
                className='section'
                title='HOLLY ROLLY POLLY!' 
                description='A simple game of roll the dice. Player will have to guess the random number generated by RNG. 
                If they got it right, they will be credited a bonus amount of tokens + the tokens they initially invest. 
                Otherwise, they do not win anything. 
                '
                join='JOIN GAME'
              />

              <Card 
                  className='section'
                  img='./Capture3.PNG' 
                  title='GAME #2'
                  description='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
                  minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                  aliquip ex ea commodo consequat. Duis aute irure dolor in
                  reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
                  pariatur.'
                  join='JOIN GAME'
                    />

              <Card 
                  className='section'
                  img='./Capture3.PNG' 
                  title='GAME #3'
                  description='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
                  minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                  aliquip ex ea commodo consequat. Duis aute irure dolor in
                  reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
                  pariatur.'
                  join='JOIN GAME'
                    />
              <Wave2/>
            </div>
    )
  }
  const Wave = () => {
    return(
      <div id="wave">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#53BAC1 " fill-opacity="1" 
        d="M0,224L40,208C80,192,160,160,240,165.3C320,171,400,213,480,240C560,267,640,277,720,240C800,203,880,
        117,960,122.7C1040,128,1120,224,1200,234.7C1280,245,1360,171,1400,133.3L1440,96L1440,0L1400,0C1360,0,1280,
        0,1200,0C1120,0,1040,0,960,0C880,0,800,0,720,0C640,0,560,0,480,0C400,0,320,0,240,0C160,0,80,0,40,0L0,0Z">
        </path>
        </svg>
      </div>
    )
  }

  const Header = () => {
    return(
      <div className= 'header'>
        <span className= 'header-title'>
          WELCOME TO THE LOTTERY GAME
        </span>
        <br/>
      </div>
    );
  }

  const Image = () => {
    return(
      <div className= 'logo'>
        <YourSvg style={{ height: 300, width: 300}}/>
        
        </div>
    )
  }

  const Card = (props) =>{
    return(
      <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gridGap: 20 }}>
        <div></div>
        <div className={props.className} >
            <div className="small-div">
                <i className={props.className}></i>
                <img src={props.img} alt=''/>
            </div>

            <div className="big-div">
                <span className='div-title'>
                    {props.title}
                </span>
                <br/>
                <span className='div-description'>
                    {props.description}
                </span>
            </div>
            <br/>
            <div className="join-game">
              <span className='join-game'>
                {props.join}
              </span>
            </div>
            
        </div>
        </div>
    )
  }

  const Wave2 = () => {
    return(
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#F7C200 " fill-opacity="1" 
      d="M0,224L40,208C80,192,160,160,240,165.3C320,171,400,213,480,240C560,267,640,277,720,240C800,203,880,117
      ,960,122.7C1040,128,1120,224,1200,234.7C1280,245,1360,171,1400,133.3L1440,96L1440,320L1400,320C1360,320,
      1280,320,1200,320C1120,320,1040,320,960,320C880,320,800,320,720,320C640,320,560,320,480,320C400,320,320,320,
      240,320C160,320,80,320,40,320L0,320Z"></path></svg>
    )
  }


export default Overview;